name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: presentation-framework/package-lock.json

      - name: Install dependencies
        run: |
          cd presentation-framework
          npm ci

      - name: Run linter
        run: |
          cd presentation-framework
          npm run lint

      - name: Run unit tests
        run: |
          cd presentation-framework
          npm run test:run

      - name: Build
        run: |
          cd presentation-framework
          npm run build

      - name: Install Playwright browsers
        run: |
          cd presentation-framework
          npx playwright install --with-deps

      - name: Run E2E tests
        run: |
          cd presentation-framework
          npm run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: presentation-framework/playwright-report/
          retention-days: 30

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: presentation-framework/package-lock.json

      - name: Install dependencies
        run: |
          cd presentation-framework
          npm ci

      - name: Run tests with coverage
        run: |
          cd presentation-framework
          npm run test:run -- --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: presentation-framework/coverage
          flags: unittests
          name: codecov-presentation-framework
